<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__organizationName</name>
   <tag></tag>
   <elementGuidId>05316f52-9414-4fb2-acd4-6e3561daabca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organizationName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organizationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcb8c9f0-9afb-4dea-85b7-f70199472fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organizationName</value>
      <webElementGuid>940f71d2-cd76-4c92-8ca8-b5d200fb8221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d441553f-b74e-4c22-aee6-69f8b9f64acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organizationName</value>
      <webElementGuid>e4fa4434-b68d-4d86-97e7-b46722a3db20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02bafcac-d5e5-4c35-94b1-16f6f55e768e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Organization Name</value>
      <webElementGuid>09b641d8-6e1a-40ad-ac46-ad60b2f5ef67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organizationName&quot;)</value>
      <webElementGuid>a3d76f3c-b4b9-4e9d-8631-814953482179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organizationName']</value>
      <webElementGuid>2a5846db-0f5f-4001-8620-187f0a44ce12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>629015e7-43a5-495d-bb5f-5edb75cd6ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'organizationName' and @type = 'text' and @id = 'organizationName' and @placeholder = 'Organization Name']</value>
      <webElementGuid>05eef88a-d60d-4a39-b04f-04be011ae2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
