<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__zipcode</name>
   <tag></tag>
   <elementGuidId>46ff1fe0-6318-4588-ac7d-ce461b0b5180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b13b1a1c-21b6-4814-b957-7c61d55205e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>e8f87992-e469-4579-ab86-9b8e6807d5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0e7d6d3-1cad-49ba-9bd3-758fbcc3a052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>19988f83-fda0-402e-99a0-9dc6029a89c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98d12557-4787-4bac-adb6-071472370809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip/Postal Code</value>
      <webElementGuid>408a0c62-1f37-4669-8629-1f2540266956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipcode&quot;)</value>
      <webElementGuid>bb85fc03-0909-4e6f-aa9d-8ba71be38e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zipcode']</value>
      <webElementGuid>db3d5a3b-4ecf-4a11-9031-ca6a952b93d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>8729e650-d3c6-4cee-8c73-2748056cd094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'zipcode' and @type = 'text' and @id = 'zipcode' and @placeholder = 'Zip/Postal Code']</value>
      <webElementGuid>524b3a3f-8f53-42f5-a72b-18480ad93fa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
