<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GSTIN</name>
   <tag></tag>
   <elementGuidId>0edda730-25b0-459f-bfd1-ec8099651090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GSTIN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GSTIN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e17c718f-9566-4512-9ba3-59977b1fc06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GSTIN</value>
      <webElementGuid>9769eb3a-dd3b-42e1-beff-b59bdf99394f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c624dff9-6eed-4b0d-819c-0a2349a4795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GSTIN</value>
      <webElementGuid>77ead96f-9507-4af2-8bf7-56610544722e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>83f14a39-964d-4ddf-ae38-5b041e143a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CIN/GSTIN</value>
      <webElementGuid>edffd344-0b97-4eb6-a7b6-c9004493e81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GSTIN&quot;)</value>
      <webElementGuid>32bcff71-70fa-4102-a77e-6518ce2b67b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GSTIN']</value>
      <webElementGuid>59809deb-213b-4aef-9a24-51161945a3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>60b68354-d22d-405f-ad8e-6d36e7643dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'GSTIN' and @type = 'text' and @id = 'GSTIN' and @placeholder = 'CIN/GSTIN']</value>
      <webElementGuid>4cdbaaa4-6991-4db5-8c06-b6e7eb84a8aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
