<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Form Builder</name>
   <tag></tag>
   <elementGuidId>e3de79c1-4474-4ef6-be88-5bc9ff141963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/aside/div/div/div/div[2]/div/div/div/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d1c1f49-4a4c-4144-a826-4b514df2680f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gap-3 nav-link</value>
      <webElementGuid>4f9d031a-2688-4c42-be39-2eac715b42e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/asset-modeller/assetmodeller</value>
      <webElementGuid>7092f962-6d5e-4f2e-bcf6-a6a5a9f31317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form Builder</value>
      <webElementGuid>d0f66175-f16d-4887-8248-05fac5ee3790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;ltr&quot;]/div[@class=&quot;pageWrapper d-md-block d-lg-flex&quot;]/aside[@class=&quot;sidebarArea&quot;]/div[@class=&quot;sidebarBox shadow bg-white fixedSidebar&quot;]/div[1]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/div[@class=&quot;p-3 pt-4 d-none d-lg-block d-sm-none border-end&quot;]/ul[@class=&quot;nav flex-column&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;gap-3 nav-link&quot;]</value>
      <webElementGuid>10c655ec-740c-41b0-939e-7326c032d63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/aside/div/div/div/div[2]/div/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>0e43b85f-db78-4fbf-9790-e04722f53840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[2]/following::a[1]</value>
      <webElementGuid>76db43ee-c234-4da4-8be1-0835d2b94a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::a[2]</value>
      <webElementGuid>c0875ec5-2ef4-4d02-ad4f-8ae133724fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planner'])[2]/preceding::a[1]</value>
      <webElementGuid>952b1c57-44fe-40ca-b19a-f5966303be44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/asset-modeller/assetmodeller')])[2]</value>
      <webElementGuid>2f1e0763-f2ba-4087-8470-ce3e5d87e776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>66e85b12-4269-4efd-a8ea-361251e7674d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/asset-modeller/assetmodeller' and (text() = 'Form Builder' or . = 'Form Builder')]</value>
      <webElementGuid>a794958c-31d4-43ab-ba76-dd7ec5308cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
