<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Super Admin</name>
   <tag></tag>
   <elementGuidId>40a905a5-d844-45ed-8317-a820296e399c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.d-flex.justify-content-center.align-items-center.dropdown-toggle.btn.btn-transparent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe9ea789-5254-41bb-b99a-d495ff61555d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fff9201-edb9-4194-86c4-0314da4a25b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d8858f6-6cd8-448b-826a-c35837c0952c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ee7dc6d-0591-4264-ac63-b65a899f95f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex justify-content-center align-items-center dropdown-toggle btn btn-transparent</value>
      <webElementGuid>a3769db0-132e-4f9e-ae39-a7bb45e192cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Super Admin </value>
      <webElementGuid>d65c56ad-8584-413e-97a5-44afe6c59bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;ltr&quot;]/div[@class=&quot;pageWrapper d-md-block d-lg-flex&quot;]/div[@class=&quot;contentArea fixedTopbar&quot;]/nav[@class=&quot;topbar border-bottom navbar navbar-expand-lg navbar-dark bg-white&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;hov-dd dropdown&quot;]/button[@class=&quot;d-flex justify-content-center align-items-center dropdown-toggle btn btn-transparent&quot;]</value>
      <webElementGuid>80643a59-31af-4efa-acbf-89e88f26b02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>405c6463-aa4e-482b-8428-7c5c49e4ec64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/nav/div/div[3]/div/button</value>
      <webElementGuid>66a51c16-0cae-4f17-b64a-cf08696acfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planner'])[2]/following::button[3]</value>
      <webElementGuid>bf1f4114-3aa8-4dba-8b3e-0e8ecb27cf7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Builder'])[2]/following::button[3]</value>
      <webElementGuid>c7c1bca2-bc19-4e87-9929-964770caae49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>9f6544f3-723a-424c-b9e5-95610e774915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Super Admin ' or . = 'Super Admin ')]</value>
      <webElementGuid>45f8fb54-999d-4675-b268-7ca3f6e806ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
